import time
from playsound import playsound
from threading import Thread
import os

os.system('cls')
def play():
    playsound("SomeBody's Pleasure.mp3")
def lyric1():
    print("Playing : SomeBody's Pleasure.")
    time.sleep(0.2)
    print("it", end=' ' ,flush=True)
    time.sleep(1)
    print("was", end=' ' ,flush=True)
    time.sleep(0.6)
    print("in", end=' ' ,flush=True)
    time.sleep(0.6)
    print("a", end=' ' ,flush=True)
    time.sleep(0.6)
    print("blink", end=' ' ,flush=True)
    time.sleep(0.6)
    print("of", end=' ' ,flush=True)
    time.sleep(0.4)
    print("an", end=' ' ,flush=True)
    time.sleep(0.5)
    print("eye", end=' ' ,flush=True)
    time.sleep(0.3)
    
    os.system('cls')
    print("Playing : SomeBody's Pleasure.")
    print("Find", end=' ' ,flush=True)
    time.sleep(0.2)
    print("a", end=' ' ,flush=True)
    time.sleep(0.2)
    print("way", end=' ' ,flush=True)
    time.sleep(0.2)
    print("how", end=' ' ,flush=True)
    time.sleep(0.2)
    print("to", end=' ' ,flush=True)
    time.sleep(0.2)
    print("say", end=' ' ,flush=True)
    time.sleep(0.3)
    print("Goodbye..", end=' ' ,flush=True)
    time.sleep(1.5)
    
    os.system('cls')
    print("Playing : SomeBody's Pleasure.")
    time.sleep(1)
    print("l've", end=' ' ,flush=True)
    time.sleep(0.8)
    print("got", end=' ' ,flush=True)
    time.sleep(0.7)
    print("to", end=' ' ,flush=True)
    time.sleep(0.7)
    print("take", end=' ' ,flush=True)
    time.sleep(0.7)
    print("me ", end=' ' ,flush=True)
    time.sleep(0.6)
    print("away", end=' ' ,flush=True)
    time.sleep(0.7)
    
    os.system('cls')
    print("Playing : SomeBody's Pleasure.")
    print("From", end=' ' ,flush=True)
    time.sleep(1)
    print("all", end=' ' ,flush=True)
    time.sleep(1)
    print("Sadness", end=' ' ,flush=True)
    time.sleep(2.2)
    
    os.system('cls')
    print("Playing : SomeBody's Pleasure.")
    print("Stitch", end=' ' ,flush=True)
    time.sleep(0.5)
    print("all", end=' ' ,flush=True)
    time.sleep(0.5)
    print("my", end=' ' ,flush=True)
    time.sleep(0.5)
    print("wounds", end=' ' ,flush=True)
    time.sleep(0.5)
    
    os.system('cls')
    print("Playing : SomeBody's Pleasure.") 
    time.sleep(0.1)
    print("Confess", end=' ' ,flush=True)
    time.sleep(0.5)
    print("all", end=' ' ,flush=True)
    time.sleep(0.5)
    print("the", end=' ' ,flush=True)
    time.sleep(0.5)
    print("sins", end=' ' ,flush=True)
    time.sleep(0.5)
    
    os.system('cls')
    print("Playing : SomeBody's Pleasure.") 
    print("And", end=' ' ,flush=True)
    time.sleep(0.4)
    print("took", end=' ' ,flush=True)
    time.sleep(0.5)
    print("all", end=' ' ,flush=True)
    time.sleep(0.4)
    print("my", end=' ' ,flush=True)
    time.sleep(0.6)
    print("insecure", end=' ' ,flush=True)
    time.sleep(1.9)
    
    os.system('cls')
    print("Playing : SomeBody's Pleasure.")
    print("When", end=' ' ,flush=True)
    time.sleep(0.9)
    print("will", end=' ' ,flush=True)
    time.sleep(0.7)
    print("l", end=' ' ,flush=True)
    time.sleep(0.7)
    print("got", end=' ' ,flush=True)
    time.sleep(0.5)
    print("the", end=' ' ,flush=True)
    time.sleep(0.7)
    print("love", end=' ' ,flush=True)
    time.sleep(0.5)
    
    os.system('cls')
    print("Playing : SomeBody's Pleasure.")
    print("That", end=' ' ,flush=True)
    time.sleep(0.5)
    print("is", end=' ' ,flush=True)
    time.sleep(0.7)
    print("so", end=' ' ,flush=True)
    time.sleep(0.7)
    print("pure?", end=' ' ,flush=True)
    time.sleep(3)
    
    os.system('cls')
    print("Playing : SomeBody's Pleasure.")
    print("Gotta", end=' ' ,flush=True)
    time.sleep(0.5)
    print("have", end=' ' ,flush=True)
    time.sleep(0.5)
    print("to", end=' ' ,flush=True)
    time.sleep(0.5)
    print("always", end=' ' ,flush=True)
    time.sleep(0.4)
    print("make", end=' ' ,flush=True)
    time.sleep(0.5)
    print("sure", end=' ' ,flush=True)
    time.sleep(1)
    
    os.system('cls')
    print("Playing : SomeBody's Pleasure.")
    print("That", end=' ' ,flush=True)
    time.sleep(0.5)
    print("l'm", end=' ' ,flush=True)
    time.sleep(0.6)
    print("not", end=' ' ,flush=True)
    time.sleep(0.6)
    print("just", end=' ' ,flush=True)
    time.sleep(0.5)
    print("SomeBody's", end=' ' ,flush=True)
    time.sleep(0.9)
    print("Preasure...", end=' ' ,flush=True)
    time.sleep(1)
    
t1=Thread(target=play)
t1.start()
t2=Thread(target=lyric1)
t2.start()    